apiVersion: batch/v1
kind: CronJob
metadata:
  name: apm-error-monitor
  namespace: elastic-stack
  labels:
    app: apm-error-monitor
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: apm-error-monitor
        spec:
          restartPolicy: OnFailure
          containers:
          - name: monitor
            image: apm-error-monitor:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: apm-monitor-config
            - secretRef:
                name: apm-monitor-secret
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"

